# Generated by Django 4.2.2 on 2023-07-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='detail',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
