# Generated by Django 4.2.2 on 2023-07-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_club_detail_club_members_alter_club_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='detail',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='members',
            field=models.FloatField(default=None, null=True),
        ),
    ]
