# Generated by Django 4.2.2 on 2023-07-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_alter_club_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='members',
            field=models.IntegerField(),
        ),
    ]
