# Generated by Django 4.2.2 on 2023-07-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='club',
        ),
    ]
