# Generated by Django 4.2.2 on 2023-07-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_rename_name_comment_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='detail',
            field=models.CharField(max_length=500),
        ),
    ]
